# Generated by Django 4.1.4 on 2023-01-02 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Edtudiante',
            new_name='Estudiante',
        ),
    ]
